// <auto-generated />
using System;
using EchoBook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EchoBook.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723022412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EchoBook.Models.AudioCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioFilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ChunkHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.Property<string>("Voice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChunkHash", "Voice", "Speed")
                        .IsUnique();

                    b.ToTable("AudioCaches");
                });

            modelBuilder.Entity("EchoBook.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EpubFilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RecoveryKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecoveryKeyId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("EchoBook.Models.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LinesPerPage")
                        .HasColumnType("integer");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<string>("PreviewText")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ChapterId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("EchoBook.Models.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<string>("EpubItemHref")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "Order");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("EchoBook.Models.ReadingProgress", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentChapterId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentScrollOffset")
                        .HasColumnType("integer");

                    b.Property<int>("LinesPerPage")
                        .HasColumnType("integer");

                    b.Property<double>("ReadingSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("SelectedVoice")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BookId");

                    b.ToTable("ReadingProgresses");
                });

            modelBuilder.Entity("EchoBook.Models.RecoveryKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastAccessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RecoveryKeys");
                });

            modelBuilder.Entity("EchoBook.Models.Settings", b =>
                {
                    b.Property<Guid>("RecoveryKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("AiVoice")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("boolean");

                    b.Property<string>("Font")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FontSize")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("LetterSpacing")
                        .HasColumnType("double precision");

                    b.Property<double>("LineHeight")
                        .HasColumnType("double precision");

                    b.Property<int>("LinesPerPage")
                        .HasColumnType("integer");

                    b.Property<double>("ReadingSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("RecoveryKeyId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("EchoBook.Models.Book", b =>
                {
                    b.HasOne("EchoBook.Models.RecoveryKey", "RecoveryKey")
                        .WithMany("Books")
                        .HasForeignKey("RecoveryKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecoveryKey");
                });

            modelBuilder.Entity("EchoBook.Models.Bookmark", b =>
                {
                    b.HasOne("EchoBook.Models.Book", "Book")
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EchoBook.Models.Chapter", "Chapter")
                        .WithMany("Bookmarks")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("EchoBook.Models.Chapter", b =>
                {
                    b.HasOne("EchoBook.Models.Book", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("EchoBook.Models.ReadingProgress", b =>
                {
                    b.HasOne("EchoBook.Models.Book", "Book")
                        .WithOne("ReadingProgress")
                        .HasForeignKey("EchoBook.Models.ReadingProgress", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("EchoBook.Models.Settings", b =>
                {
                    b.HasOne("EchoBook.Models.RecoveryKey", "RecoveryKey")
                        .WithOne("Settings")
                        .HasForeignKey("EchoBook.Models.Settings", "RecoveryKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecoveryKey");
                });

            modelBuilder.Entity("EchoBook.Models.Book", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Chapters");

                    b.Navigation("ReadingProgress");
                });

            modelBuilder.Entity("EchoBook.Models.Chapter", b =>
                {
                    b.Navigation("Bookmarks");
                });

            modelBuilder.Entity("EchoBook.Models.RecoveryKey", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
